### ISSUE TITLE
Expect session id in `"session-id"` key rather than `"session_id"`

### ISSUE THREAD

**Issue by vivekashok1221** [idkbrowby/gamingrealm-frontend#13]
Since https://github.com/idkbrowby/gamingrealm-backend/commit/57089bbbfeaaffbebc806e860ff36880b36d2561 got merged, the session id of the logged in user will now be set in `"session-id"` key of the response from the backend server.

All references to `"session_id"` has to be updated to `"session-id"`.

**Comment by anand2312** [comment]
Thanks to openapi-fetch generating types, all accesses to session id is now forced to be with `"session-id"` - see [example type](https://github.com/idkbrowby/gamingrealm-frontend/blob/main/src/lib/api_schema.d.ts#L210-L216)
